### ISSUE TITLE
Creating learning curves in parallel not working

### ISSUE THREAD

**Issue by lhjohn** [OHDSI/PatientLevelPrediction#177]
**Describe the bug**
An error is thrown when creating learning curves in parallel using `createLearningCurvePar()`. See screenshot below.

**Set up (please run in R "sessionInfo()" and copy the output here):**
R 4.0.2, 64 Bit
All packages (CRAN/OHDSI) updated on 16 August 2020.

**To Reproduce**
I could reproduce the problem on Ubuntu 18.04 and macOS 10.15 by creating any learning curve in parallel using 8 core machines with sufficient memory.

**Additional context**
![Screenshot from 2020-08-16 14-25-23](https://user-images.githubusercontent.com/7384198/90334606-28906f00-dfcf-11ea-857b-4635a0f878f8.png)

**Comment by jreps** [comment]
Hi Henrik - I noticed the result when the runPlp() fails due to a warning or error was 2 short and I think this was the issue (rbind was failing). I've fixed this so the error should go away.  However, this means some of the results you want are not being returned due to errors/warnings in the runPlp - I think I added this as the parallel code seems to fails due to warnings - but I can turn the return NULL on warning off and see whether it works for you?

**Comment by jreps** [comment]
The warnings are likely to to low outcome counts - I could also remove the warnings in the runPlp and make them logInfo instead...

**Comment by jreps** [comment]
Actually - it may be the depreciation warning due to the split - try using the split: 'stratified' instead of 'person'

**Comment by lhjohn** [comment]
Hi Jenna, thanks for looking into this. I tried a few things but still no luck.

1. Using "stratified" gave the same error.
2. Using "stratified" + your latest fix/commit returned a learning curve object with 0 in all fields. Can you check if this snippet works for you?

```
set.seed(1234)
data(plpDataSimulationProfile)
sampleSize <- 2000
plpData <- PatientLevelPrediction::simulatePlpData(plpDataSimulationProfile, n = sampleSize)
population <- PatientLevelPrediction::createStudyPopulation(plpData, outcomeId = 2,
learningCurve <- PatientLevelPrediction::createLearningCurve(plpData = plpData, population = population, modelSettings = PatientLevelPrediction::setLassoLogisticRegression(seed = 1000), splitSeed = 1000, testSplit = "stratified", testFraction = 0.2, trainFractions = seq(0.1, 0.8, 0.1))
```

In my previously implementation of parallel learning curves I have entirely omitted prediction models that threw an error. These errors would occur a lot for small training fractions, because, as you mentioned, not enough outcomes were present.

**Comment by jreps** [comment]
PatientLevelPrediction::createLearningCurvePar and PatientLevelPrediction::createLearningCurve both run with that example code to completion and return the same result for me.

You must be getting some warning for some reason?  Try PatientLevelPrediction::createLearningCurve and see whether you see any warning pop up?

**Comment by lhjohn** [comment]
The sequential function works fine without any warning under macOS and ubuntu, but the parallelized function does not give any warning and returns all fields with 0. I will test around a bit more.

**Comment by lhjohn** [comment]
We could try something like this and assign the variable `memory` to the `RAM` input.

```
# determine operating system type
  if(.Platform$OS.type == "windows") {
    memory <- utils::memory.size()
  } else if (.Platform$OS.type == "unix") {
    memory <- NULL
  } else {
    memory <- NULL
  }
```

**Comment by lhjohn** [comment]
Resolved with latest pull request.
