### ISSUE TITLE
Error when training a Naive Bayes PLP model. 

### ISSUE THREAD

**Issue by nbehzad** [OHDSI/PatientLevelPrediction#301]
**Describe the bug**
After training the final model using optimal parameters and calculating predictions on all train data, the following attribute error occurs: `'GaussianNB' object has no attribute 'feature_importances_' `

**Set up (please run in R "sessionInfo()" and copy the output here):**
R version 4.1.3 (2022-03-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.2.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] shiny_1.7.1                  yaml_2.3.5                   log4r_0.4.2                  SqlRender_1.9.0              BQJdbcConnectionStringR_0.1 
 [6] PatientLevelPrediction_5.0.5 FeatureExtraction_3.2.0      Andromeda_0.6.0              dplyr_1.0.9                  DatabaseConnector_5.0.2     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8.3         here_1.0.1           lattice_0.20-45      tidyr_1.2.0          png_0.1-7            rprojroot_2.0.3     
 [7] assertthat_0.2.1     digest_0.6.29        utf8_1.2.2           mime_0.12            plyr_1.8.7           R6_2.5.1            
[13] RSQLite_2.2.12       ggplot2_3.3.5        pillar_1.8.0         rlang_1.0.4          rstudioapi_0.13      blob_1.2.3          
[19] Matrix_1.4-0         reticulate_1.24      labeling_0.4.2       bit_4.0.4            munsell_0.5.0        compiler_4.1.3      
[25] httpuv_1.6.5         pkgconfig_2.0.3      htmltools_0.5.2      tidyselect_1.1.2     tibble_3.1.8         gridExtra_2.3       
[31] fansi_1.0.3          memuse_4.2-1         crayon_1.5.1         dbplyr_2.1.1         withr_2.5.0          later_1.3.0         
[37] grid_4.1.3           jsonlite_1.8.0       xtable_1.8-4         gtable_0.3.0         lifecycle_1.0.1      DBI_1.1.2           
[43] magrittr_2.0.3       pROC_1.18.0          scales_1.2.0         zip_2.2.0            cli_3.3.0            cachem_1.0.6        
[49] farver_2.1.0         promises_1.2.0.1     ellipsis_0.3.2       generics_0.1.3       vctrs_0.4.1          tools_4.1.3         
[55] bit64_4.0.5          glue_1.6.2           ParallelLogger_3.0.1 purrr_0.3.4          hms_1.1.1            fastmap_1.1.0       
[61] colorspace_2.0-3     memoise_2.0.1        rJava_1.0-6         
/Users/behzadn/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/sklearn/utils/deprecation.py:103: FutureWarning: Attribute `sigma_` was deprecated in 1.0 and will be removed in1.2. Use `var_` instead.
  warnings.warn(msg, category=FutureWarning)

**To Reproduce**
library(PatientLevelPrediction)
source("src/databaseConnection.R")

runSinglePrediction <- function(config, logger, readPlpData = T) {

    connectionDetails <- getConnectionDetails(config, logger)
    databaseDetails <- getDatabaseDetails(connectionDetails, config, logger)
    
    covariateSettings <- createCovariateSettings(
      useDemographicsGender = TRUE,
      useDemographicsAgeGroup = TRUE,
      useDemographicsRace = TRUE,
      useDemographicsEthnicity = TRUE,
      
      useConditionOccurrenceMediumTerm = TRUE,
      useProcedureOccurrenceMediumTerm = TRUE,
      useDrugExposureMediumTerm = TRUE,
      useMeasurementMediumTerm = TRUE,
      
      useConditionGroupEraMediumTerm = TRUE,
      useDrugGroupEraMediumTerm = TRUE,
      
      useDistinctConditionCountMediumTerm = TRUE,
      useDistinctProcedureCountMediumTerm = TRUE,
      useDistinctIngredientCountMediumTerm = TRUE,
      useDistinctMeasurementCountMediumTerm = TRUE,
      
      mediumTermStartDays = -180,
      endDays = 0
    )
    
    if (readPlpData) {
      plpData <- loadPlpData("./plpSingleOutput/plpData")
    } else {
      plpData <- getPlpData(
        databaseDetails = databaseDetails,
        covariateSettings = covariateSettings,
        restrictPlpDataSettings = createRestrictPlpDataSettings()
      )
      savePlpData(plpData, "./plpSingleOutput/plpData")
    }
    
    populationSettings <- createStudyPopulationSettings(
      washoutPeriod = 0,
      firstExposureOnly = FALSE,
      removeSubjectsWithPriorOutcome = FALSE,
      priorOutcomeLookback = 9999,
      riskWindowStart = 90,
      riskWindowEnd = 180,
      minTimeAtRisk = 90,
      startAnchor = 'cohort start',
      endAnchor = 'cohort start',
      requireTimeAtRisk = TRUE,
      includeAllOutcomes = TRUE
    )

    splitSettings <- createDefaultSplitSetting(
      trainFraction = 0.80,
      testFraction = 0.20,
      type = 'stratified',
      nfold = 5,
      splitSeed = 13
    )
    
    preprocessSettings <- createPreprocessSettings(
      minFraction = 0.001,
      normalize = T,
      removeRedundancy = T
    )
    
    executeSettings <- createExecuteSettings(
      runSplitData = T,
      runSampleData = T,
      runfeatureEngineering = T,
      runPreprocessData = T,
      runModelDevelopment = T,
      runCovariateSummary = T
    )
    
    plpResult <- runPlp(
      plpData = plpData,
      outcomeId = config$cdm$outcome_cohort_id,
      analysisId = "Analysis 1",
      analysisName = "Naive Bayes",
      populationSettings = populationSettings,
      splitSettings = splitSettings,
      sampleSettings = createSampleSettings(),
      featureEngineeringSettings = createFeatureEngineeringSettings(),
      preprocessSettings = preprocessSettings,
      modelSettings = setNaiveBayes(),
      logSettings = createLogSettings(),
      executeSettings = executeSettings,
      saveDirectory = "plpSingleOutput"
    )
    plotPlp(plpResult = plpResult,
            saveLocation = file.path("plpSingleOutput","NB", "plots"))
    return (plpResults)
  }

**PLP Log File**
2022-08-11 16:24:09	[Main thread]	DEBUG	PatientLevelPrediction	checkInputs	binary : TRUEincludeAllOutcomes : TRUEfirstExposureOnly : FALSEwashoutPeriod : 0removeSubjectsWithPriorOutcome : FALSEpriorOutcomeLookback : 9999requireTimeAtRisk : TRUEminTimeAtRisk : 90riskWindowStart : 90startAnchor : cohort startriskWindowEnd : 180endAnchor : cohort startrestrictTarToCohortEnd : FALSE
2022-08-11 16:24:09	[Main thread]	DEBUG	PatientLevelPrediction	checkInputs	test : 0.2train : 0.8seed : 13nfold : 5
2022-08-11 16:24:09	[Main thread]	DEBUG	PatientLevelPrediction	checkInputs	numberOutcomestoNonOutcomes : 1sampleSeed : 7094
2022-08-11 16:24:09	[Main thread]	DEBUG	PatientLevelPrediction	checkInputs	 : 
2022-08-11 16:24:09	[Main thread]	DEBUG	PatientLevelPrediction	checkInputs	minFraction : 0.001normalize : TRUEremoveRedundancy : TRUE
2022-08-11 16:24:09	[Main thread]	DEBUG	PatientLevelPrediction	checkInputs	fitFunction : fitSklearnparam : true
2022-08-11 16:24:09	[Main thread]	DEBUG	PatientLevelPrediction	checkInputs	runSplitData : TRUErunSampleData : TRUErunfeatureEngineering : TRUErunPreprocessData : TRUErunModelDevelopment : TRUErunCovariateSummary : TRUE
2022-08-11 16:24:09	[Main thread]	INFO	PatientLevelPrediction	printHeader	Patient-Level Prediction Package version 5.0.5
2022-08-11 16:24:09	[Main thread]	INFO	PatientLevelPrediction	printHeader	Study started at: 2022-08-11 16:24:09
2022-08-11 16:24:09	[Main thread]	INFO	PatientLevelPrediction	printHeader	AnalysisID:         NB
2022-08-11 16:24:09	[Main thread]	INFO	PatientLevelPrediction	printHeader	AnalysisName:       PORPOISE
2022-08-11 16:24:09	[Main thread]	INFO	PatientLevelPrediction	printHeader	CohortID:           1
2022-08-11 16:24:09	[Main thread]	INFO	PatientLevelPrediction	printHeader	OutcomeID:          2
2022-08-11 16:24:09	[Main thread]	INFO	PatientLevelPrediction	printHeader	Cohort size:        31842
2022-08-11 16:24:09	[Main thread]	INFO	PatientLevelPrediction	printHeader	Covariates:         31161
2022-08-11 16:24:09	[Main thread]	DEBUG	PatientLevelPrediction		outcomeId: 2
2022-08-11 16:24:09	[Main thread]	DEBUG	PatientLevelPrediction		binary: TRUE
2022-08-11 16:24:09	[Main thread]	DEBUG	PatientLevelPrediction		includeAllOutcomes: TRUE
2022-08-11 16:24:09	[Main thread]	DEBUG	PatientLevelPrediction		firstExposureOnly: FALSE
2022-08-11 16:24:09	[Main thread]	DEBUG	PatientLevelPrediction		washoutPeriod: 0
2022-08-11 16:24:09	[Main thread]	DEBUG	PatientLevelPrediction		removeSubjectsWithPriorOutcome: FALSE
2022-08-11 16:24:09	[Main thread]	DEBUG	PatientLevelPrediction		priorOutcomeLookback: 9999
2022-08-11 16:24:09	[Main thread]	DEBUG	PatientLevelPrediction		requireTimeAtRisk: TRUE
2022-08-11 16:24:09	[Main thread]	DEBUG	PatientLevelPrediction		minTimeAtRisk: 90
2022-08-11 16:24:09	[Main thread]	DEBUG	PatientLevelPrediction		restrictTarToCohortEnd: FALSE
2022-08-11 16:24:09	[Main thread]	DEBUG	PatientLevelPrediction		riskWindowStart: 90
2022-08-11 16:24:09	[Main thread]	DEBUG	PatientLevelPrediction		startAnchor: cohort start
2022-08-11 16:24:09	[Main thread]	DEBUG	PatientLevelPrediction		riskWindowEnd: 180
2022-08-11 16:24:09	[Main thread]	DEBUG	PatientLevelPrediction		endAnchor: cohort start
2022-08-11 16:24:09	[Main thread]	DEBUG	PatientLevelPrediction		restrictTarToCohortEnd: FALSE
2022-08-11 16:24:09	[Main thread]	INFO	PatientLevelPrediction		Outcome is 0 or 1
2022-08-11 16:24:09	[Main thread]	DEBUG	PatientLevelPrediction	checkInputsSplit	test: 0.2
2022-08-11 16:24:09	[Main thread]	DEBUG	PatientLevelPrediction	checkInputsSplit	train: 0.8
2022-08-11 16:24:09	[Main thread]	DEBUG	PatientLevelPrediction	checkInputsSplit	nfold: 5
2022-08-11 16:24:09	[Main thread]	INFO	PatientLevelPrediction	checkInputsSplit	seed: 13
2022-08-11 16:24:09	[Main thread]	INFO	PatientLevelPrediction		Creating a 20% test and 80% train (into 5 folds) random stratified split by class
2022-08-11 16:24:09	[Main thread]	INFO	PatientLevelPrediction		Data split into 6367 test cases and 25475 train cases (5096, 5095, 5095, 5095, 5094)
2022-08-11 16:24:32	[Main thread]	INFO	PatientLevelPrediction	dataSummary	Train Set:
2022-08-11 16:24:32	[Main thread]	INFO	PatientLevelPrediction	dataSummary	Fold 1 5096 patients with 765 outcomes - Fold 2 5095 patients with 765 outcomes - Fold 3 5095 patients with 765 outcomes - Fold 4 5095 patients with 765 outcomes - Fold 5 5094 patients with 764 outcomes
2022-08-11 16:24:32	[Main thread]	INFO	PatientLevelPrediction	dataSummary	29549 covariates in train data
2022-08-11 16:24:32	[Main thread]	INFO	PatientLevelPrediction	dataSummary	Test Set:
2022-08-11 16:24:32	[Main thread]	INFO	PatientLevelPrediction	dataSummary	6367 patients with 955 outcomes
2022-08-11 16:24:32	[Main thread]	INFO	PatientLevelPrediction	sampleData	Starting data sampling
2022-08-11 16:24:32	[Main thread]	INFO	PatientLevelPrediction	sampleData	Applying sameData
2022-08-11 16:24:32	[Main thread]	INFO	PatientLevelPrediction		No sampling - returning same data
2022-08-11 16:24:32	[Main thread]	INFO	PatientLevelPrediction	sampleData	Finished data sampling
2022-08-11 16:24:32	[Main thread]	INFO	PatientLevelPrediction	dataSummary	Train Set:
2022-08-11 16:24:33	[Main thread]	INFO	PatientLevelPrediction	dataSummary	Fold 1 5096 patients with 765 outcomes - Fold 2 5095 patients with 765 outcomes - Fold 3 5095 patients with 765 outcomes - Fold 4 5095 patients with 765 outcomes - Fold 5 5094 patients with 764 outcomes
2022-08-11 16:24:33	[Main thread]	INFO	PatientLevelPrediction	dataSummary	29549 covariates in train data
2022-08-11 16:24:33	[Main thread]	INFO	PatientLevelPrediction	dataSummary	Test Set:
2022-08-11 16:24:33	[Main thread]	INFO	PatientLevelPrediction	dataSummary	6367 patients with 955 outcomes
2022-08-11 16:24:33	[Main thread]	INFO	PatientLevelPrediction	featureEngineer	Starting Feature Engineering
2022-08-11 16:24:33	[Main thread]	INFO	PatientLevelPrediction	featureEngineer	Applying sameData
2022-08-11 16:24:33	[Main thread]	INFO	PatientLevelPrediction		No sampling - returning same data
2022-08-11 16:24:33	[Main thread]	INFO	PatientLevelPrediction	featureEngineer	Done Feature Engineering
2022-08-11 16:24:33	[Main thread]	INFO	PatientLevelPrediction	dataSummary	Train Set:
2022-08-11 16:24:33	[Main thread]	INFO	PatientLevelPrediction	dataSummary	Fold 1 5096 patients with 765 outcomes - Fold 2 5095 patients with 765 outcomes - Fold 3 5095 patients with 765 outcomes - Fold 4 5095 patients with 765 outcomes - Fold 5 5094 patients with 764 outcomes
2022-08-11 16:24:33	[Main thread]	INFO	PatientLevelPrediction	dataSummary	29549 covariates in train data
2022-08-11 16:24:33	[Main thread]	INFO	PatientLevelPrediction	dataSummary	Test Set:
2022-08-11 16:24:33	[Main thread]	INFO	PatientLevelPrediction	dataSummary	6367 patients with 955 outcomes
2022-08-11 16:24:33	[Main thread]	DEBUG	PatientLevelPrediction	preprocessData	minFraction: 0.001
2022-08-11 16:24:33	[Main thread]	DEBUG	PatientLevelPrediction	preprocessData	normalize: TRUE
2022-08-11 16:24:33	[Main thread]	DEBUG	PatientLevelPrediction	preprocessData	removeRedundancy: TRUE
2022-08-11 16:24:40	[Main thread]	INFO	FeatureExtraction		Removing 0 redundant covariates
2022-08-11 16:24:40	[Main thread]	INFO	FeatureExtraction		Removing 21761 infrequent covariates
2022-08-11 16:24:40	[Main thread]	INFO	FeatureExtraction		Normalizing covariates
2022-08-11 16:24:54	[Main thread]	INFO	FeatureExtraction		Tidying covariates took 20.9 secs
2022-08-11 16:24:54	[Main thread]	INFO	PatientLevelPrediction	dataSummary	Train Set:
2022-08-11 16:24:54	[Main thread]	INFO	PatientLevelPrediction	dataSummary	Fold 1 5096 patients with 765 outcomes - Fold 2 5095 patients with 765 outcomes - Fold 3 5095 patients with 765 outcomes - Fold 4 5095 patients with 765 outcomes - Fold 5 5094 patients with 764 outcomes
2022-08-11 16:24:57	[Main thread]	INFO	PatientLevelPrediction	dataSummary	7788 covariates in train data
2022-08-11 16:24:57	[Main thread]	INFO	PatientLevelPrediction	dataSummary	Test Set:
2022-08-11 16:24:57	[Main thread]	INFO	PatientLevelPrediction	dataSummary	6367 patients with 955 outcomes
2022-08-11 16:24:57	[Main thread]	INFO	PatientLevelPrediction	runPlp	
2022-08-11 16:24:57	[Main thread]	DEBUG	PatientLevelPrediction	checkPySettings	classifier seed: 0
2022-08-11 16:24:57	[Main thread]	DEBUG	PatientLevelPrediction	checkPySettings	requiresDenseMatrix: TRUE
2022-08-11 16:24:57	[Main thread]	DEBUG	PatientLevelPrediction	checkPySettings	name: Naive Bayes
2022-08-11 16:24:57	[Main thread]	DEBUG	PatientLevelPrediction	checkPySettings	saveToJson: TRUE
2022-08-11 16:24:57	[Main thread]	DEBUG	PatientLevelPrediction	checkPySettings	pythonImport: sklearn
2022-08-11 16:24:57	[Main thread]	DEBUG	PatientLevelPrediction	checkPySettings	pythonImportSecond: naive_bayes
2022-08-11 16:24:57	[Main thread]	DEBUG	PatientLevelPrediction	checkPySettings	pythonClassifier: GaussianNB
2022-08-11 16:24:57	[Main thread]	INFO	PatientLevelPrediction	toSparseM	starting toSparseM
2022-08-11 16:24:57	[Main thread]	DEBUG	PatientLevelPrediction	toSparseM	Max covariateId in original covariates: 2000038602503
2022-08-11 16:24:57	[Main thread]	INFO	PatientLevelPrediction	MapIds	starting to map the columns and rows
2022-08-11 16:25:19	[Main thread]	INFO	PatientLevelPrediction	MapIds	finished MapCovariates
2022-08-11 16:25:19	[Main thread]	DEBUG	PatientLevelPrediction	toSparseM	# covariates in mapped covariateRef: 7788
2022-08-11 16:25:19	[Main thread]	DEBUG	PatientLevelPrediction	toSparseM	Max newCovariateId in mapping: 7788
2022-08-11 16:25:19	[Main thread]	DEBUG	PatientLevelPrediction	toSparseM	Max rowId in new : 25475
2022-08-11 16:25:20	[Main thread]	INFO	PatientLevelPrediction	toSparseM	toSparseM non temporal used
2022-08-11 16:25:20	[Main thread]	INFO	PatientLevelPrediction	checkRam	plpData size estimated to use 52.41% of available RAM (0.1GBs)
2022-08-11 16:25:33	[Main thread]	DEBUG	PatientLevelPrediction	toSparseM	Sparse matrix with dimensionality: 25475,7788
2022-08-11 16:25:33	[Main thread]	INFO	PatientLevelPrediction	toSparseM	finishing toSparseM
2022-08-11 16:25:33	[Main thread]	INFO	PatientLevelPrediction		Rnning CV for Naive Bayes model
2022-08-11 16:25:41	[Main thread]	INFO	PatientLevelPrediction		Max fold: 5
2022-08-11 16:25:41	[Main thread]	INFO	PatientLevelPrediction		Fold 1
2022-08-11 16:25:42	[Main thread]	INFO	PatientLevelPrediction		Converting sparse martix to dense matrix (CV)
2022-08-11 16:25:43	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	data X dim: 20379x7788
2022-08-11 16:25:43	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	data Y length: 20379 with 3059 outcomes
2022-08-11 16:25:43	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	:true
2022-08-11 16:25:49	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	Training model took (mins): 0.104578197002411
2022-08-11 16:25:49	[Main thread]	INFO	PatientLevelPrediction		Calculating predictions on left out fold set...
2022-08-11 16:25:50	[Main thread]	INFO	PatientLevelPrediction		Fold 2
2022-08-11 16:25:52	[Main thread]	INFO	PatientLevelPrediction		Converting sparse martix to dense matrix (CV)
2022-08-11 16:25:52	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	data X dim: 20380x7788
2022-08-11 16:25:52	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	data Y length: 20380 with 3059 outcomes
2022-08-11 16:25:52	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	:true
2022-08-11 16:25:59	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	Training model took (mins): 0.113060065110524
2022-08-11 16:25:59	[Main thread]	INFO	PatientLevelPrediction		Calculating predictions on left out fold set...
2022-08-11 16:26:00	[Main thread]	INFO	PatientLevelPrediction		Fold 3
2022-08-11 16:26:01	[Main thread]	INFO	PatientLevelPrediction		Converting sparse martix to dense matrix (CV)
2022-08-11 16:26:01	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	data X dim: 20380x7788
2022-08-11 16:26:01	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	data Y length: 20380 with 3059 outcomes
2022-08-11 16:26:01	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	:true
2022-08-11 16:26:09	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	Training model took (mins): 0.118373835086823
2022-08-11 16:26:09	[Main thread]	INFO	PatientLevelPrediction		Calculating predictions on left out fold set...
2022-08-11 16:26:10	[Main thread]	INFO	PatientLevelPrediction		Fold 4
2022-08-11 16:26:11	[Main thread]	INFO	PatientLevelPrediction		Converting sparse martix to dense matrix (CV)
2022-08-11 16:26:11	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	data X dim: 20380x7788
2022-08-11 16:26:11	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	data Y length: 20380 with 3059 outcomes
2022-08-11 16:26:11	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	:true
2022-08-11 16:26:18	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	Training model took (mins): 0.113832680384318
2022-08-11 16:26:18	[Main thread]	INFO	PatientLevelPrediction		Calculating predictions on left out fold set...
2022-08-11 16:26:19	[Main thread]	INFO	PatientLevelPrediction		Fold 5
2022-08-11 16:26:21	[Main thread]	INFO	PatientLevelPrediction		Converting sparse martix to dense matrix (CV)
2022-08-11 16:26:22	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	data X dim: 20381x7788
2022-08-11 16:26:22	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	data Y length: 20381 with 3060 outcomes
2022-08-11 16:26:22	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	:true
2022-08-11 16:26:27	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	Training model took (mins): 0.0879727323849996
2022-08-11 16:26:27	[Main thread]	INFO	PatientLevelPrediction		Calculating predictions on left out fold set...
2022-08-11 16:26:28	[Main thread]	INFO	pROC	roc.default	Setting levels: control = 0, case = 1 
2022-08-11 16:26:28	[Main thread]	INFO	pROC	roc.default	Setting levels: control = 0, case = 1 
2022-08-11 16:26:28	[Main thread]	INFO	pROC	roc.default	Setting levels: control = 0, case = 1 
2022-08-11 16:26:28	[Main thread]	INFO	pROC	roc.default	Setting levels: control = 0, case = 1 
2022-08-11 16:26:28	[Main thread]	INFO	pROC	roc.default	Setting levels: control = 0, case = 1 
2022-08-11 16:26:28	[Main thread]	INFO	pROC	roc.default	Setting levels: control = 0, case = 1 
2022-08-11 16:26:28	[Main thread]	INFO	PatientLevelPrediction		Training final model using optimal parameters
2022-08-11 16:26:29	[Main thread]	INFO	PatientLevelPrediction		Converting sparse martix to dense matrix (final model)
2022-08-11 16:26:30	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	data X dim: 25475x7788
2022-08-11 16:26:30	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	data Y length: 25475 with 3824 outcomes
2022-08-11 16:26:30	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	:true
2022-08-11 16:26:38	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	Training model took (mins): 0.141226983070374
2022-08-11 16:26:38	[Main thread]	INFO	PatientLevelPrediction		Calculating predictions on all train data...
2022-08-11 16:26:44	[Main thread]	INFO	PatientLevelPrediction	3	Error in py_get_attr_impl(x, name, silent): AttributeError: 'GaussianNB' object has no attribute 'feature_importances_' 
2022-08-11 16:26:44	[Main thread]	INFO	PatientLevelPrediction		Removing infrequent and redundant covariates and normalizing
2022-08-11 16:26:50	[Main thread]	INFO	PatientLevelPrediction	toSparseM	starting toSparseM
2022-08-11 16:26:50	[Main thread]	DEBUG	PatientLevelPrediction	toSparseM	Max covariateId in original covariates: 2000038602503
2022-08-11 16:26:50	[Main thread]	INFO	PatientLevelPrediction	MapIds	starting to map the columns and rows
2022-08-11 16:26:56	[Main thread]	INFO	PatientLevelPrediction	MapIds	finished MapCovariates
2022-08-11 16:26:56	[Main thread]	DEBUG	PatientLevelPrediction	toSparseM	# covariates in mapped covariateRef: 7788
2022-08-11 16:26:56	[Main thread]	DEBUG	PatientLevelPrediction	toSparseM	Max newCovariateId in mapping: 7788
2022-08-11 16:26:56	[Main thread]	DEBUG	PatientLevelPrediction	toSparseM	Max rowId in new : 6367
2022-08-11 16:26:56	[Main thread]	INFO	PatientLevelPrediction	toSparseM	toSparseM non temporal used
2022-08-11 16:26:56	[Main thread]	INFO	PatientLevelPrediction	checkRam	plpData size estimated to use 0.68% of available RAM (0GBs)
2022-08-11 16:26:59	[Main thread]	DEBUG	PatientLevelPrediction	toSparseM	Sparse matrix with dimensionality: 6367,7788
2022-08-11 16:26:59	[Main thread]	INFO	PatientLevelPrediction	toSparseM	finishing toSparseM
2022-08-11 16:26:59	[Main thread]	ERROR	PatientLevelPrediction	3	Error in py_call_impl(callable, dots$args, dots$keywords): FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/92/z2rtd5nj22n_q9nv57qp9srm0000gq/T//RtmpgdEKJt\\python_models_378882\\model.json' 
2022-08-11 16:26:59	[Main thread]	FATAL	PatientLevelPrediction	runPlp	numbers of columns of arguments do not match

**Comment by jreps** [comment]
Hello, the missing feature importance happens as there is no method to extract feature importance for NB but I think the error that is stopping the runPlp is a bug that happened on linux due to the way the path for the model was specified. This was fixed in the develop branch, is it possible to install the develop branch and retry the code:

remotes::install_github(repo = 'ohdsi/PatientLevelPrediction', ref = 'develop')

Please let me know if this fixes the issue.

**Comment by nbehzad** [comment]
Hi, Thank you for your information and comment! I installed the develop branch and updated all dependencies. The session information is provided below. *I ran the same code, but the problem still remains.*

**Session Info**
R version 4.1.3 (2022-03-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.2.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] FeatureExtraction_3.2.0      Andromeda_0.6.1              dplyr_1.0.9                 
[4] PatientLevelPrediction_5.4.1 yaml_2.3.5                   SqlRender_1.9.2             
[7] DatabaseConnector_5.0.4      BQJdbcConnectionStringR_0.1  log4r_0.4.2                 

loaded via a namespace (and not attached):
 [1] zip_2.2.0            Rcpp_1.0.9           plyr_1.8.7           dbplyr_2.2.1        
 [5] pillar_1.8.0         compiler_4.1.3       tools_4.1.3          bit_4.0.4           
 [9] lattice_0.20-45      jsonlite_1.8.0       RSQLite_2.2.15       memoise_2.0.1       
[13] lifecycle_1.0.1      tibble_3.1.8         png_0.1-7            pkgconfig_2.0.3     
[17] rlang_1.0.4          Matrix_1.4-0         DBI_1.1.3            cli_3.3.0           
[21] rstudioapi_0.13      fastmap_1.1.0        rJava_1.0-6          pROC_1.18.0         
[25] generics_0.1.3       vctrs_0.4.1          hms_1.1.1            rprojroot_2.0.3     
[29] grid_4.1.3           bit64_4.0.5          tidyselect_1.1.2     here_1.0.1          
[33] reticulate_1.25      glue_1.6.2           R6_2.5.1             fansi_1.0.3         
[37] ParallelLogger_3.0.1 purrr_0.3.4          blob_1.2.3           magrittr_2.0.3      
[41] ellipsis_0.3.2       assertthat_0.2.1     memuse_4.2-1         utf8_1.2.2          
[45] cachem_1.0.6         crayon_1.5.1  

**PLP Log File**
*I only included the last lines of the log file where the error occurs:*

2022-08-12 15:32:50	[Main thread]	INFO	PatientLevelPrediction		Training final model using optimal parameters
2022-08-12 15:32:50	[Main thread]	INFO	PatientLevelPrediction		Converting sparse martix to dense matrix (final model)
2022-08-12 15:32:51	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	data X dim: 24398x13793
2022-08-12 15:32:51	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	data Y length: 24398 with 3664 outcomes
2022-08-12 15:32:51	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	:true
2022-08-12 15:33:07	[Main thread]	INFO	PatientLevelPrediction	fitPythonModel	Training model took (mins): 0.255709449450175
2022-08-12 15:33:07	[Main thread]	INFO	PatientLevelPrediction		Calculating predictions on all train data...
2022-08-12 15:33:15	[Main thread]	INFO	PatientLevelPrediction	3	Error in py_get_attr_impl(x, name, silent): AttributeError: 'GaussianNB' object has no attribute 'feature_importances_'  
2022-08-12 15:33:16	[Main thread]	INFO	PatientLevelPrediction		Removing infrequent and redundant covariates and normalizing
2022-08-12 15:33:31	[Main thread]	INFO	PatientLevelPrediction	toSparseM	starting toSparseM
2022-08-12 15:33:31	[Main thread]	DEBUG	PatientLevelPrediction	toSparseM	Max covariateId in original covariates: 46287576303
2022-08-12 15:33:31	[Main thread]	INFO	PatientLevelPrediction	MapIds	starting to map the columns and rows
2022-08-12 15:33:48	[Main thread]	INFO	PatientLevelPrediction	MapIds	finished MapCovariates
2022-08-12 15:33:48	[Main thread]	DEBUG	PatientLevelPrediction	toSparseM	# covariates in mapped covariateRef: 13793
2022-08-12 15:33:48	[Main thread]	DEBUG	PatientLevelPrediction	toSparseM	Max newCovariateId in mapping: 13793
2022-08-12 15:33:48	[Main thread]	DEBUG	PatientLevelPrediction	toSparseM	Max rowId in new : 6098
2022-08-12 15:33:48	[Main thread]	INFO	PatientLevelPrediction	toSparseM	toSparseM non temporal used
2022-08-12 15:33:49	[Main thread]	INFO	PatientLevelPrediction	checkRam	plpData size estimated to use 1.66% of available RAM (0.1GBs)
2022-08-12 15:33:56	[Main thread]	DEBUG	PatientLevelPrediction	toSparseM	Sparse matrix with dimensionality: 6098,13793
2022-08-12 15:33:56	[Main thread]	INFO	PatientLevelPrediction	toSparseM	finishing toSparseM
2022-08-12 15:33:57	[Main thread]	ERROR	PatientLevelPrediction	3	Error in py_call_impl(callable, dots$args, dots$keywords): TypeError: __init__() takes 1 positional argument but 2 were given  
2022-08-12 15:33:57	[Main thread]	FATAL	PatientLevelPrediction	runPlp	numbers of columns of arguments do not match

**Error in the traceback**
```
Error in rbind(deparse.level, ...) : 
numbers of columns of arguments do not match
```
```
5. stop("numbers of columns of arguments do not match")
4. rbind(deparse.level, ...)
3. rbind(predictionTest, prediction[, colnames(prediction) != "index"])
2. runPlp(plpData = plpData, outcomeId = config$cdm$outcome_cohort_id, 
analysisId = modelName, analysisName = "naive Bayes", populationSettings = populationSettings, 
splitSettings = splitSettings, sampleSettings = createSampleSettings(), 
featureEngineeringSettings = createFeatureEngineeringSettings(), ... at singlePrediction.R#147
1. runSinglePrediction(config, logger, modelName = "NB", readPlpData = T)
```

Thanks,
Behzad

**Comment by jreps** [comment]
There seems to be a python error now.   I just tested locally and I get the same error "Error in py_call_impl(callable, dots$args, dots$keywords): TypeError: GaussianNB.__init__() takes 1 positional argument but 2 were given" - my have been some update with sklearn where possibly the inputs have changed.  I'll see what had changed.

**Comment by jreps** [comment]
Ok - the issue seemed to be caused by saving the model as a json and loading is - I made a small modification and it works for me now.  I updated the develop branch with the fix.

**Comment by nbehzad** [comment]
Thank you so much! I tried it out. It worked, and the issue was solved, but you have disabled saving the model as a json file. As a result, the model object in the plpResult (`plpResult$model$model`) is missing. Is it causing issues later on, such as when loading the model in the Shiny app?

**Comment by jreps** [comment]
I think there was a different issue breaking the shiny app (I removed the trainDetails from the database as they were too large in some cases to be saved in the database, so I save them in a file linked to the database instead - but this broke the shiny app).  When I tested the latest code the shiny app worked - except the calibration plot - so I need to figure out what is breaking that (it may be a warning breaking it).

**Comment by jreps** [comment]
Closing this now as I've pushed the fixes for the sklearn models (had to remove the saving to json).  The shiny app should work - please ensure you have the latest version of OhdsiShinyModules since the shiny code is now in that package.
